import React, { useState } from 'react';
import QueryForm from './components/QueryForm';
import ResponseDisplay from './components/ResponseDisplay';

const App = () => {
  const [response, setResponse] = useState('');
  const [ownerResponse, setOwnerResponse] = useState('');

  const handleQuerySubmit = async (query) => {
    try {
      
      const responseFromServer = await fetch('/api/query', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ query }),
      });

      if (!responseFromServer.ok) {
        throw new Error('Failed to fetch response from the server');
      }

      const responseData = await responseFromServer.json();
      setResponse(responseData.autoGeneratedResponse);
      setOwnerResponse(responseData.ownerResponse);
    } catch (error) {
      console.error('Error:', error.message);
    }
  };

  return (
    <div>
      <h1>ThoughtThrive</h1>
      <QueryForm onSubmit={handleQuerySubmit} />
      <ResponseDisplay response={response} />
      <div>
        <strong>Owner's Response:</strong> {ownerResponse}
      </div>
    </div>
  );
};

export default App;
