const Query = require('../models/Query');

const handleQuery = async (req, res) => {
  try {
    
    const { query: userQuery } = req.body;

   
    const queryResult = await Query.findOne({ query: userQuery });

    if (!queryResult) {
      
      res.status(404).json({ error: 'No result found for the query' });
      return;
    }

  
    const { autoGeneratedResponse } = queryResult;

    
    const ownerResponse = `Owner's response for the query: ${userQuery}`;
    res.json({ autoGeneratedResponse, ownerResponse });
  } catch (error) {
    console.error('Error in handleQuery:', error);
    res.status(500).json({ error: 'Internal Server Error' });
  }
};

module.exports = {
  handleQuery,
};
